### ISSUE TITLE
Fix Needed !!

### ISSUE THREAD

**Issue by BROTOKARMOKAR** [Ezz-Kun/Comz3#1]
@Ezz-Kun  assalam sir .
I need your help very badly..
I can't run this compiling script . Plz fix this ... I just want to learn this ,,,

Script : [LINK](https://gist.githubusercontent.com/BROTOKARMOKAR/236cfb43f404c7d9e0eca10f675e0fb3/raw/)

### Plz Sir ... 😭 😭 😭

**Comment by Ezz-Kun** [comment]
> @Ezz-Kun assalam sir .
> I need your help very badly..
> I can't run this compiling script . Plz fix this ... I just want to learn this ,,,
> 
> Script : [LINK](https://gist.githubusercontent.com/BROTOKARMOKAR/236cfb43f404c7d9e0eca10f675e0fb3/raw/)
> 
> ### Plz Sir ... 😭 😭 😭

This is correct, but only works in Python 2.7 ...

https://pastebin.com/raw/7sMTQ2RW

**Comment by BROTOKARMOKAR** [comment]
thanks a lot sir 😄
